// <auto-generated />
namespace Carrick.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Carrick : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Carrick));
        
        string IMigrationMetadata.Id
        {
            get { return "201604120512429_Carrick"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
